baseURL = "https://errorstates.com"
languageCode = "en-us"
title = "Error States"
theme = "amperage"

# Number of posts shown per page (default: 10)
paginate = 10

# Menu elements
[[menu.main]]
    identifier = "home"
    name = "error states"
    url = "https://errorstates.com"
    weight = 10

pygmentsUseClasses = true

# Enable only tags taxonomy
[taxonomies]
    tag = "tags"

[params]
    copyright = "error states" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker"]

    # Google Analytics code
    googleAnalytics = "UA-158622898-1"

    # Adsense publisher code
    # adsensePublisher = "ca-pub-123456789"

    # Comments Iframe URL
    # commentsEmbedUrl = "https://comments.example.com"

    # Social sites for metatags
    # facebookSite = "example"
    # twitterSite = "@example"

    # Structured data elements
    # socialProfiles = ["https://twitter.com/example","https://www.linkedin.com/in/example/","https://github.com/example"]

    alternatePageName = "Error States"
    organizationLogo = "/logo.png"
    organizationName = "Error States"

    publisherName = "Error States"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60

[markup]
    defaultMarkdownHandler = "blackfriday"