baseURL = "https://errorstates.github.io/"
languageCode = "en-us"
title = "Error States"
theme = "amperage"

# Number of posts shown per page (default: 10)
paginate = 10

# Menu elements
[[menu.main]]
    identifier = "home"
    name = "Error States"
    url = "https://errorstates.github.io"
    weight = 10
[[menu.main]]
    identifier = "Submit"
    name = "Submit"
    url = "https://errorstates.github.io/submit/"
    weight = 10

pygmentsUseClasses = true

# Enable only tags taxonomy
[taxonomies]
    tag = "tags"

[params]
    copyright = "ErrorStates" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker"]

    # Google Analytics code
    # googleAnalytics = "UA-xxxxxxxxx-x"

    # Adsense publisher code
    # adsensePublisher = "ca-pub-123456789"

    # Comments Iframe URL
    # commentsEmbedUrl = "https://comments.example.com"

    # Social sites for metatags
    facebookSite = "example"
    twitterSite = "@example"

    # Structured data elements
    socialProfiles = ["https://twitter.com/example","https://www.linkedin.com/in/example/","https://github.com/example"]

    alternatePageName = "Amperage example"
    organizationLogo = "/logo.png"
    organizationName = "Error States"

    publisherName = "Error States"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60

[markup]
    defaultMarkdownHandler = "blackfriday"