name = "Error States"

license = "MIT"
licenselink = "https://github.com/asurbernardo/amperage/blob/master/LICENSE"

description = "Modified Amperage Theme for ErrorStates.com"

homepage = "https://github.com/asurbernardo/amperage"

tags = ["blog", "personal", "responsive", 'minimal', 'clean', "simple", "google analytics", "light",
    "multilingual", "syntax highlighting", "fast", "customizable", "minimalistic", "technical", "amp",
    "white", "disqus", "starter"]

features = ["amp", "seo", "pwa", "structured data", "toc", "related content", "service-worker", "shortcodes",
    "syntax highlighting", "tags", "social share"]

min_version = "0.59.0"

[author]
    name = "Roman Kudryashov"
    homepage = "Roman Design Co."
